language: python
python: "3.6"
sudo: false
cache: pip
env:
  - TOXENV=py27-django111
  - TOXENV=py34-django111
  - TOXENV=py35-django111
  - TOXENV=py36-django111
  - TOXENV=py34-django20
  - TOXENV=py35-django20
  - TOXENV=py36-django20
  - TOXENV=py37-django20
  - TOXENV=py35-django21
  - TOXENV=py36-django21
  - TOXENV=py37-django21
  - TOXENV=py35-django20
  - TOXENV=py36-django22
  - TOXENV=py37-django22
  - TOXENV=docs
  - TOXENV=lint
matrix:
  include:
    - python: "3.5"
      env: TOXENV=py35-django111
    - python: "3.5"
      env: TOXENV=py35-django20
    - python: "3.5"
      env: TOXENV=py35-django21
    - python: "3.5"
      env: TOXENV=py35-django22
  exclude:
    - python: "3.6"
      env: TOXENV=py35-django111
    - python: "3.6"
      env: TOXENV=py35-django20
    - python: "3.6"
      env: TOXENV=py35-django21
    - python: "3.6"
      env: TOXENV=py35-django22
install:
  - pip install tox
script:
  - tox -e $TOXENV
